blog/symfony/src/Entity/Post.php
<?php

namespace App\Entity;

use App\Entity\Resources\CreatedUpdatedInterface;
use App\Entity\Resources\SluggableInterface;
use App\Entity\Resources\CreatedUpdatedTrait;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

// use Symfony\Component\Validator\Constraints\Collection;
// use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

// @UniqueEntity("slug")
/**
 * @ORM\Table(name="posts")
 * @ORM\Entity(repositoryClass="App\Repository\PostRepository")
 */
class Post implements SluggableInterface, CreatedUpdatedInterface
{
    use CreatedUpdatedTrait;

    /* Columns */

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text")
     */
    private $text;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $textShort;

    // было unique=true, но пост ищется по id, поэтому конфликта не будет, ничего страшного думаю не будет
    // если одинаковый слуг, он же относится к контенту, не нужно будет делать проверку уникальнсоти слугов и для
    // сохранения уникальности добавлять число на конец слуга, которое только будет мешать seo(не относится к заголовку)
    // Например, допустим посты начали писать разные пользователи, один сделал пост со слугом "kak-rabotat-s-symfony-4"
    // (Как работать с Symfony 4), потом второй сделал такой же заголовок, но слуг уже будет "kak-rabotat-s-symfony-42"
    // (добавилось 2 для уникальности слуга), получилось что версия не 4, а 42, как по мне, это меняет смысл поста,
    // из-за чего плохо для сео.
    /**
     * @ORM\Column(name="slug", type="string", length=255)
     */
    private $slug;

    /* Relations */

//    /**
//     * @ORM\OneToMany(targetEntity="App\Entity\Comment", mappedBy="post", orphanRemoval=true)
//     * @ORM\JoinColumn(referencedColumnName="id", onDelete="CASCADE")
//     */
//    private $comments;

    /**
     * @ORM\ManyToMany(targetEntity="Tag")
     * @ORM\JoinTable(
     *   name="post_tag",
     *   joinColumns={
     *     @ORM\JoinColumn(name="post_id", referencedColumnName="id")
     *   },
     *   inverseJoinColumns={
     *     @ORM\JoinColumn(name="tag_id", referencedColumnName="id")
     *   }
     * )
     */
    private $tags;

    //, inversedBy="posts"
    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User")
     * @ORM\JoinColumn(referencedColumnName="id", onDelete="CASCADE")
     */
    private $author;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\PostVote", mappedBy="post", orphanRemoval=true)
     * @ORM\JoinColumn(referencedColumnName="id", onDelete="CASCADE")
     * @ORM\OrderBy(value={"createdAt" = "DESC"})
     */
    private $votes;

    /**
     * Post constructor.
     * @param User $author
     * @param string $title
     * @param string $text
     * @param string $textShort
     * @param Tag[] $tags
     */
    public function __construct(User $author, string $title, string $text, string $textShort, $tags = [])
    {
//        $this->comments = new ArrayCollection();
        $this->votes = new ArrayCollection();
        $this->tags = new ArrayCollection();

        foreach ($tags as $tag) {
            $this->addTag($tag);
        }

//        $author->addPost($this);
        $this
            ->setAuthor($author)
            ->setTitle($title)
            ->setText($text)
            ->setTextShort($textShort);
    }

    public function getSlugAttributes(): array
    {
        return [
            // TODO если указывать метод setSlug => setTitle то их использовать
            'slug' => 'title'
        ];
    }

    /* Getters / Setters */

    public function getId(): int
    {
        return $this->id;
    }

    public function getTitle(): string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getText(): string
    {
        return $this->text;
    }

    public function setText(string $text): self
    {
        $this->text = $text;

        return $this;
    }

    public function getTextShort(): string
    {
        return $this->textShort;
    }

    public function setTextShort(string $textShort): self
    {
        $this->textShort = $textShort;

        return $this;
    }

    public function getSlug(): string
    {
        return $this->slug;
    }

    /* Relations */

    public function getVotesValue(): int
    {
//        $sum = array_reduce(
//            $this->votes->toArray(),
//            function ($perv, PostVote $curr) {
//                return $perv + $curr->getValue();
//            }
//        );

        $sum = array_sum(
            array_map(function (PostVote $vote) {
                return $vote->getValue();
            }, $this->votes->toArray())
        );

        return $sum;
    }

    public function getVotes(): Collection
    {
        return $this->votes;
    }

    public function addVote(PostVote $vote): self
    {
        if (!$this->votes->contains($vote)) {
            $this->votes[] = $vote;
        }

        return $this;
    }

    public function removeVote(PostVote $vote): self
    {
        if ($this->votes->contains($vote)) {
            $this->votes->removeElement($vote);
            // set the owning side to null (unless already changed)
            if ($vote->getPost() === $this) {
                $vote->setPost(null);
            }
        }

        return $this;
    }

    public function getTags(): Collection
    {
        return $this->tags;
    }

    public function addTag(Tag $tag): self
    {
        if (!$this->tags->contains($tag)) {
            $this->tags[] = $tag;
        }

        return $this;
    }

    public function getAuthor(): User
    {
        return $this->author;
    }

    public function setAuthor(User $author): self
    {
        $this->author = $author;

        return $this;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    /* Other */

    public function getUserVoteValue(User $user): ?Int
    {
        if (!$vote = $this->getUserVote($user)) {
            return null;
        }

        return $vote->getValue();
        // Если бы PHP возвращал не bool для логических: return ($vote = $this->getUserVote($user)) && $vote->getValue()
    }

    /**
     * @param User $user
     * @return PostVote | null
     */
    public function getUserVote(User $user): ?PostVote
    {
        $foundVote = null;

        // не нашел более удобную функцию :( Нужно как find в JS.
        $this->votes->forAll(function ($key, PostVote $vote) use ($user, &$foundVote) {
            if ($vote->getUser()->getId() === $user->getId()) {
                $foundVote = $vote;

                return false;
            }

            return true;
        });

        return $foundVote;
    }
}

blog/symfony/src/Form/DataObjects/Post/PostData.php
<?php

namespace App\Form\DataObjects\Post;

use Symfony\Component\Validator\Constraints as Assert;

final class PostData
{

}

blog/symfony/src/Form/Post/PostCreationFormType.php
<?php

namespace App\Form\Post;

use App\Form\DataObjects\Post\PostData;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PostCreationFormType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
//        $builder
//            ->add('')
//        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => PostData::class,
        ]);
    }
}

blog/symfony/templates/blog/posts/parts/commentsLvl.html.twig
<div class="comments-wrap ml-5 my-2">
  {% for comment in comments %}
      {#<b-card class="comments ml-4 mb-2">#}
      {{ blogDate(comment.getCreatedAt()) }}

      <p class="card-text">
        {{ comment.text }}
        <br>
        {#<b-button#}
          {#size="sm"#}
          {#variant="secondary"#}
        {#>#}
          {#Reply#}
        {#</b-button>#}

        <b-btn
          v-b-toggle.collapse-for-comment{{ comment.id }}
          size="sm"
          variant="secondary"
        >
          Reply
        </b-btn>
        <b-collapse id="collapse-for-comment{{ comment.id }}" class="mt-2">
          <b-form @submit="onSubmit">
            <b-form-group
              id="exampleInputGroup1"
              label="Email address:"
              label-for="exampleInput1"
              description="We'll never share your email with anyone else."
            >
              ${ formComment.text }
              <b-form-input
                v-model="formComment.text"
                id="exampleInput1"
                type="text"
                placeholder="Enter text"
                required
              >
              </b-form-input>
            </b-form-group>

            <b-button type="submit" variant="primary">
              Submit
            </b-button>
          </b-form>
        </b-collapse>
      </p>

      <hr>

      {#не хотел два раза вызывать, не знаю плохо ли тут set юзать#}
      {% set comments = comment.getChildrenComments() %}

      {% if comments | length > 0 %}
        {% include 'blog/posts/parts/commentsLvl.html.twig' with { comments: comments, isRoot: false, form: form } only %}
      {% endif %}

      {#</b-card>#}
  {% endfor %}
</div>

blog/symfony/templates/blog/posts/parts/comments_tree.html.twig
<div class="comments-wrap">
  {% for comment in comments %}
    <div class="comment">
      {#<b-card class="comments ml-4 mb-2">#}

      <div class="comment__self-content">
        By
        <b>
          {{ comment.author.username }}
        </b>

        {{ blogDate(comment.createdAt) }}

        <div class="comment__text editor-view-content">
          {{ comment.text | raw }}
        </div>

        {% if is_granted('IS_AUTHENTICATED_FULLY') and comment.author.id is same as(app.user.id) %}
          <b-btn
            size="sm"
            variant="primary"
          >
            Edit
          </b-btn>
        {% endif %}
        {% if is_granted('IS_AUTHENTICATED_FULLY') %}
          <b-btn
            v-b-toggle.collapse-for-comment{{ comment.id }}
            size="sm"
            variant="secondary"
          >
            Reply
          </b-btn>
          <b-collapse id="collapse-for-comment{{ comment.id }}" class="mt-2">
            <create-comment
              parent-comment-id="{{ comment.id }}"
              api-endpoint="{{ path('post_create_comment', { slug: commentsPost.slug, id: commentsPost.id }) }}"
            ></create-comment>
            {#
            <b-form
              @submit="onSubmit"
              action="{{ url('post', { slug: commentsPost.slug, id: commentsPost.id}) }}"
              method="post"
            >
              <b-form-group
                label="Email address:"
                label-for="comment-{{ comment.id }}-input-message"
                description="Please, provide a good message."
              >
                <input type="hidden" name="token" value="{{ csrf_token('create-comment-item') }}" />

                <b-form-input
                  v-model="formComment.text"
                  id="comment-{{ comment.id }}-input-message"
                  type="text"
                  placeholder="Enter text"
                  required
                >
                </b-form-input>
              </b-form-group>

              <b-button type="submit" variant="primary">
                Submit
              </b-button>
            </b-form>
            #}
          </b-collapse>
        {% endif %}
      </div>


      {#<hr>#}

      {% set childrenComments = comment.getChildrenComments() %}

      {% if childrenComments | length > 0 %}
        {# не уверен что стоит так делать, комменты же имеют одинаковый пост,
        не хотел писать commentsPost: commentsPost как ты мне замечание сделал с comments: comments #}
        {% set childrenCommentsPost = commentsPost %}

        {% include 'blog/posts/parts/comments_tree.html.twig' with { commentsPost: childrenCommentsPost, comments: childrenComments } only %}
      {% endif %}

      {#</b-card>#}
    </div>
  {% endfor %}
</div>

blog/symfony/templates/blog/posts/parts/rating_button.html.twig
<b-btn id="post-{{ ratingPost.id }}-rating-popover-button" variant="primary">
  Rating:

  {% if ratingPost.votesValue > 3 %}
    <b-badge variant="success">
      {{ ratingPost.votesValue }}
    </b-badge>
  {% elseif ratingPost.votesValue < -3 %}
    <b-badge variant="danger">
      {{ ratingPost.votesValue }}
    </b-badge>
  {% else %}
    <b-badge variant="light">
      {{ ratingPost.votesValue }}
    </b-badge>
  {% endif %}
</b-btn>

{% if is_granted('IS_AUTHENTICATED_FULLY') and votingActivate is defined and votingActivate %}
  <form
    action="{{ path('post_do_vote', { id: ratingPost.id }) }}"
    method="POST"
    class="d-inline"
  >
    <input type="hidden" name="token" value="{{ csrf_token('user_vote') }}">
    <input type="hidden" name="voteValue" value="+1">

    <b-button
      type="submit"
      size="small"
      variant="{% if not ratingPost.userVoteValue(app.user) is same as(1) %}outline-{% endif %}success"
    >
      👍🏻
    </b-button>
  </form>

  <form
    action="{{ path('post_do_vote', { id: ratingPost.id }) }}"
    method="POST"
    class="d-inline"
  >
    <input type="hidden" name="token" value="{{ csrf_token('user_vote') }}">
    <input type="hidden" name="voteValue" value="-1">

    <b-button
      type="submit"
      size="small"
      variant="{% if not ratingPost.userVoteValue(app.user) is same as(-1) %}outline-{% endif %}danger"
    >
      👎🏻
    </b-button>
  </form>
{% endif %}

blog/symfony/templates/blog/posts/parts/rating_popover.html.twig
{# Этот элемент зависит от blog/posts/parts/rating_popover.html.twig #}

{% set limit = 6 %}

<b-popover
  target="post-{{ ratingPost.id }}-rating-popover-button"
  title="Last votes"
  triggers="hover"
  placement="bottom"
>
  <div style="text-overflow: ellipsis; white-space: nowrap; overflow: hidden;">
    {% for vote in ratingPost.votes | slice(0, limit) %}
      <b-badge variant="{{ vote.value == -1 ? 'danger' : 'success' }}">
        {{ vote.value }}
      </b-badge>

      <b>
        {{ vote.user.username }}
      </b>

      <br>

      {{ blogDate(vote.createdAt) }}
      <hr class="my-0 py-0">
    {% endfor %}
    {% if ratingPost.votes | length > limit %}
      And more ({{ ratingPost.votes | length - limit }} votes)...
    {% endif %}
  </div>
</b-popover>